### ISSUE TITLE
visible ESP when spectating would be awesome

### ISSUE THREAD

**Issue by exscreamo** [Fr0go1/Aeonix-Cs2#1]
i just tried ur latest version, nice work.

**Comment by Fr0go1** [comment]
> i just tried ur latest version, nice work.

thanks i will se if i can add a option to keep the visuals up even when dead

**Comment by exscreamo** [comment]
someone posted this, maybe u can try this

https://github.com/TKazer/CS2_External/issues/42#issuecomment-1753619459

**Comment by Fr0go1** [comment]
> someone posted this, maybe u can try this
> 
> [TKazer/CS2_External#42 (comment)](https://github.com/TKazer/CS2_External/issues/42#issuecomment-1753619459)

ok thanks i will look into adding it. might not be today as im sick

**Comment by Fr0go1** [comment]
> someone posted this, maybe u can try this
> 
> [TKazer/CS2_External#42 (comment)](https://github.com/TKazer/CS2_External/issues/42#issuecomment-1753619459)

i added it

**Comment by exscreamo** [comment]
> > someone posted this, maybe u can try this
> > 
> > [TKazer/CS2_External#42 (comment)](https://github.com/TKazer/CS2_External/issues/42#issuecomment-1753619459)
> 
> i added it

will try this. thankyou so much!
