### ISSUE TITLE
What is that offset in Offsets.h?

### ISSUE THREAD

**Issue by DollarKVier** [Fr0go1/Aeonix-Cs2#15]
### Discussed in https://github.com/Fr0go1/Aeonix-Cs2/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **DollarKVier** October 12, 2023</sup>
What exactly is the DWORD Pos Offset? cause all offsets are renamed...</div>

**Comment by Fr0go1** [comment]
DWORD Pos = 0xCD8;

**Comment by DollarKVier** [comment]
No I meant what is the real name of the netvar
