### ISSUE TITLE
Aimbot very choppy when playing online

### ISSUE THREAD

**Issue by juicyman69** [Fr0go1/Aeonix-Cs2#2]

**Comment by juicyman69** [comment]
When i play against bots the aimbot works like a charm but in a real match its very choppy and going crazy

**Comment by Fr0go1** [comment]
> When i play against bots the aimbot works like a charm but in a real match its very choppy and going crazy

I am planing to fully rework the aimbot but until then i wouldnt recommend using it and you have a change of getting vac

**Comment by juicyman69** [comment]
or is reading memory also flagged/dtc?

**Comment by Fr0go1** [comment]
> > > When i play against bots the aimbot works like a charm but in a real match its very choppy and going crazy
> > 
> > 
> > I am planing to fully rework the aimbot but until then i wouldnt recommend using it and you have a change of getting vac
> 
> a question. would the cheat be completely undetected if i removed removed stuff that writes memory and only keep like esp & trigger?

wont change anything if you didnt use the features as it only writes to mem if you enable it. and reading mem is also detectable but nowhere near as much as writing
