### ISSUE TITLE
Failed to update offsets. After recent game update

### ISSUE THREAD

**Issue by xKrillexx** [Fr0go1/Aeonix-Cs2#22]
After a recent game update, I can't get it to work. 

![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/147776713/5644ce29-8c49-429c-869b-cb7413baa7bb)

**Comment by Soduem** [comment]
re install?

**Comment by yl1337** [comment]
reinstall what the game?

**Comment by Fr0go1** [comment]
fixed
