### ISSUE TITLE
SpottedByMask acting weird

### ISSUE THREAD

**Issue by chuckmorris420** [Fr0go1/Aeonix-Cs2#25]
Seems to be chosing the wrong pawn to show as visible after today's update.

https://streamable.com/86ncmk

**Comment by Fr0go1** [comment]
i think i fixed

**Comment by chuckmorris420** [comment]
It now will only highlight an enemy if they have spotted you, doesn't matter if you spot them.
The UI changes for VisCheck don't work for me also, cannot enable or change colours. Have to use an old config with VisCheck enabled and the color already set. (I tried making a new config aswell with no joy)

https://streamable.com/1q6xet

**Comment by Corgansm** [comment]
config issue, get gud

**Comment by chuckmorris420** [comment]
> config issue, get gud
I highly doubt my config effects the logic of the code on vischeck..
