### ISSUE TITLE
can i get ban?

### ISSUE THREAD

**Issue by urfavmonkeycheats** [Fr0go1/Aeonix-Cs2#3]
can i get ban like the main src or no ?

**Comment by Fr0go1** [comment]
> can i get ban like the main src or no ?

you have a chance if you use aimbot/rcs and bhop due to them changing the games view angles and force jumping. I am planing to make the aimbot use mouse_event in the future so it is fully ud.

**Comment by juicyman69** [comment]
> > can i get ban like the main src or no ?
> 
> you have a chance if you use aimbot/rcs and bhop due to them changing the games view angles and force jumping. I am planing to make the aimbot use mouse_event in the future so it is fully ud.

that sounds very cool, is there any eta? and also really clean looking gui!

**Comment by Fr0go1** [comment]
> > > can i get ban like the main src or no ?
> > 
> > 
> > you have a chance if you use aimbot/rcs and bhop due to them changing the games view angles and force jumping. I am planing to make the aimbot use mouse_event in the future so it is fully ud.
> 
> that sounds very cool, is there any eta? and also really clean looking gui!

thanks, i am open to suggestions with the ui. Also i dont have a eta although it is quite high on ly list of thinks to do
