### ISSUE TITLE
ESP Preview is scuffed

### ISSUE THREAD

**Issue by chuckmorris420** [Fr0go1/Aeonix-Cs2#33]
Cuts menu in half and sometimes flickers

![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/33428878/b9545695-ed32-4560-bb57-8a15483fba96)
![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/33428878/86df7d9c-1e18-4500-b7e5-cbb546316fc4)
![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/33428878/6e1b4096-1932-43ca-94a1-0ec303658403)

**Comment by Fr0go1** [comment]
you edited the code so it is a issue with your code

**Comment by chuckmorris420** [comment]
Are you sure? I really don't think that's the case. 
All I did was remove the Aimbot tab which has no code overlap with the ESP preview. 
If anything it seemed to be tied to the title of the ImGUI menu (User, menu name, fps and time). It places the preview at the end of the text.
![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/33428878/a2db5a83-9da0-446a-bb9d-1dc82a746ecb)
![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/33428878/e66225b0-6687-46be-a6f2-1d02aeb3e448)
When I would have only the FPS it does this
![image](https://github.com/Fr0go1/Aeonix-Cs2/assets/33428878/c7d0a9bd-228c-4a07-933a-d4b12103d0e0)

**Comment by Fr0go1** [comment]
its because it attatches to the window name and you changed it so it messed up
