### ISSUE TITLE
Issues i've found

### ISSUE THREAD

**Issue by OvertimeDev-Random** [Fr0go1/Aeonix-Cs2#36]
Issue: Esp cutting out on one player.
Issue: Fov seems to no matter when vischeck is off for aimbot. (It locks on to them even tho they are outside the fov)
Issue: Vischeck (Players can be right infront of you and vischeck thinks they arent)

Also side note to fix watermark fps do
 float fps = 1.0f / ImGui::GetIO().DeltaTime; 
 
  //fps
 if (MenuConfig::watermarkfps)
     ImGui::Text("%.1f fps", fps);
 ImGui::SameLine();
 
 Ps. Will edit when i find more if i do.

**Comment by Fr0go1** [comment]
i am actively fixing aimbot in the v2 version and i have fixed fps in v2
