### ISSUE TITLE
how to make it into another language？

### ISSUE THREAD

**Issue by KGB121** [Fr0go1/Aeonix-Cs2#7]
thanks a lot

**Comment by Fr0go1** [comment]
> thanks a lot

not sure as i have never done it, you can prob ask https://github.com/TKazer

**Comment by zerodev-exe** [comment]
> Why change the language? C++ is the best language for gamehacking, this cheat is pretty well optimized, so I don't see any point in trying to change this language. But if you really want to rewrite it you need to learn both languages, and try to rewrite it.
What about rust?

**Comment by Fr0go1** [comment]
> > Why change the language? C++ is the best language for gamehacking, this cheat is pretty well optimized, so I don't see any point in trying to change this language. But if you really want to rewrite it you need to learn both languages, and try to rewrite it.
> > What about rust?

its not worth the time, just use cpp
